---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false

  vars_prompt:

    - name: registry_pwd
      prompt: What is your password for registry.redhat.io?

  tasks:

  - name: 01 install ansible collection
    ansible.builtin.shell: |
      ansible-galaxy collection install community.general
      ansible-galaxy collection install ansible.posix
      ansible-galaxy collection install containers.podman
  
  - name: get full operator list
    include_role:
      name: operator-list
    vars:
      soure_operator_index: redhat-operator-index
      registry_user: jinzha1@redhat.com
      disk_dev: /dev/sda



      #operator_list:
      #- local-storage-operator
      #- mcg-operator
      #- ocs-operator
      #- odf-csi-addons-operator
      #- odf-operator
